---
title: "IMMORTOOL-use-from-R"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IMMORTOOL-use-from-R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# General background

```{r setup}
library(IMMORTOOL)
```



```{r}
cohort.size <- 5e6 #stable to 2 dp
set.seed(1234)
```


TODO use of shiny app
TODO define below classes of paper



# First set of examples


## van der Vaart

```{r,fig.dim=c(7,6)}
## Main result (demonstration naive analysis)
ans.vanderVaart <- makeResultList(
                      mortality.times = c(7,30,90),
                      mortality.fracs = c(0.05,0.21,0.31),
                      treatment.times = c(6,9,13,90),
                      treatment.fracs = c(0.09,0.19,0.28,0.37),
                      N = 147, Tmax = 90, Tlandmark = 1,
                      plotfit = TRUE,
                      simulation.cohort.size = cohort.size)

```

## Jones and Fowler

```{r,fig.dim=c(7,6)}

## mortality
tzm <- c(1,2,3,4,5,6,7,8,9,10,11,12,90)
fzm <- c(0.01,0.04,0.05,0.05,0.06,0.07,0.08,0.08,0.09,0.11,0.12,0.13,0.20)

## treatment
tzt <- c(1,2,45)
fzt <- c(0.73,0.84,0.93)

## Main result 
ans.JonesandFowler <- makeResultList(mortality.times = tzm,
                                     mortality.fracs = fzm,
                                     treatment.times = tzt,
                                     treatment.fracs = fzt,
                                     N = 117, Tmax = 90, Tlandmark = 1,
                                     plotfit = TRUE,
                                     simulation.cohort.size = cohort.size)

```
NOTE should we have Tearly=2? But these analyses not used?


## Geleris

```{r,fig.dim=c(7,6)}
tzm <- c(1,30)
fzm <- c(0.05,0.25)
tzt <- c(0.1,1,9)
fzt <- c(0.27,0.51,0.59)

## Standard assumptions
ans.Geleris <- makeResultList(mortality.times = tzm,
                              mortality.fracs = fzm,
                              treatment.times = tzt,
                              treatment.fracs = fzt,
                              N=346,Tmax=30,Tlandmark=2,
                              plotfit = TRUE,
                              simulation.cohort.size = cohort.size)
```


## Combined

```{r}
## Calculate confidence intervals: make list of all results
nmz <- c('van der Vaart','Jones and Fowler','Geleris')
L <- list(ans.vanderVaart,ans.JonesandFowler,ans.Geleris)
names(L) <- nmz

## create table from results list
tab <- makeCItable(L)

## show just the id and RR+CIs:
knitr::kable(tab[,c('id','CI.a','CI.b','CI.c','CI.d')])

```

NOTE could modify above to grey out the irrelevant cells?


# Second set of examples


```{r}
Tmax <- 30
Tlandmark <- 1
```


## Adalat

```{r,fig.dim=c(7,6)}
## Standard assumptions
ans.Adalat.standard <- makeResultList(mortality.times = c(2,8,30),
                                      mortality.fracs = c(0.07,0.14,0.14),
                                      treatment.times = c(0.5,30),
                                      treatment.fracs = c(0.19,0.38),
                                      N = 3, Tmax = Tmax, Tlandmark = Tlandmark,
                                      plotfit = TRUE,
                                      simulation.cohort.size = cohort.size)

## Low ITB assumptions
ans.Adalat.low <- makeResultList(mortality.times = c(2,8,30),
                                 mortality.fracs = c(0.05,0.14,0.14),
                                 treatment.times = c(0.25,30),
                                 treatment.fracs = c(0.19, 0.38),
                                 N = 3, Tmax = Tmax, Tlandmark = Tlandmark,
                                 simulation.cohort.size = cohort.size)

## High ITB assumptions
ans.Adalat.high <- makeResultList(mortality.times = c(2,8,30),
                                  mortality.fracs = c(0.10,0.14,0.14),
                                  treatment.times = c(1, 30),
                                  treatment.fracs = c(0.19, 0.38),
                                  N = 3, Tmax = Tmax, Tlandmark = Tlandmark,
                                  simulation.cohort.size = cohort.size)


```


## Carapetis

```{r,fig.dim=c(7,6)}

## Standard assumptions
ans.Carapetis.standard <- makeResultList(mortality.times = c(2,8,30),
                                         mortality.fracs = c(0.09,0.19,0.19),
                                         treatment.times = c(0.5,30),
                                         treatment.fracs = c(0.18,0.35),
                                         N = 7, Tmax = Tmax, Tlandmark = Tlandmark,
                                         plotfit = TRUE,
                                         simulation.cohort.size = cohort.size)

## Low ITB assumptions
ans.Carapetis.low <- makeResultList(mortality.times = c(2,8,30),
                                    mortality.fracs = c(0.06,0.19,0.19),
                                    treatment.times = c(0.25,30),
                                    treatment.fracs = c(0.18,0.35),
                                    N = 7, Tmax = Tmax, Tlandmark = Tlandmark,
                                    simulation.cohort.size = cohort.size)

## High ITB assumptions
ans.Carapetis.high <- makeResultList(mortality.times = c(2,8,30),
                                     mortality.fracs = c(0.13,0.19,0.19),
                                     treatment.times = c(1,30),
                                     treatment.fracs = c(0.18,0.35),
                                     N = 7, Tmax = Tmax, Tlandmark = Tlandmark,
                                     simulation.cohort.size = cohort.size)


```



## Linner

```{r,fig.dim=c(7,6)}

## Standard assumptions
ans.Linner.standard <- makeResultList(mortality.times = c(2,8,30),
                                      mortality.fracs = c(0.13,0.27,0.27),
                                      treatment.times = c(0.5,30),
                                      treatment.fracs = c(0.2,0.4),
                                      N = 14, Tmax = Tmax, Tlandmark = Tlandmark,
                                      plotfit = TRUE,
                                      simulation.cohort.size = cohort.size)

## Low ITB assumptions
ans.Linner.low <- makeResultList(mortality.times = c(2,8,30),
                                 mortality.fracs = c(0.09,0.27,0.27),
                                 treatment.times = c(0.25,30),
                                 treatment.fracs = c(0.2,0.4),
                                 N = 14, Tmax = Tmax, Tlandmark = Tlandmark,
                                 simulation.cohort.size = cohort.size)

## High ITB assumptions
ans.Linner.high <- makeResultList(mortality.times = c(2,8,30),
                                  mortality.fracs = c(0.18,0.27,0.27),
                                  treatment.times = c(1,30),
                                  treatment.fracs = c(0.2,0.4),
                                  N = 14, Tmax = Tmax, Tlandmark = Tlandmark,
                                  simulation.cohort.size = cohort.size)

```



## Combined

```{r}
### Calculate confidence intervals: make list of all results
nmz <- c('Adalat.standard','Carapetis.standard','Linner.standard',
         'Adalat.low','Carapetis.low','Linner.low',
         'Adalat.high','Carapetis.high','Linner.high')
L <- list(ans.Adalat.standard,ans.Carapetis.standard,ans.Linner.standard,
          ans.Adalat.low,ans.Carapetis.low,ans.Linner.low,
          ans.Adalat.high,ans.Carapetis.high,ans.Linner.high)
names(L) <- nmz


## create table from results list
tab <- makeCItable(L)

## show just the id and RR+CIs for naive only:
knitr::kable(tab[,c('id','CI.a')])

```

# Examples using internals of above

TODO